module.exports = {
    DEFAULT: undefined,
    WAITING_FOR_REPO: 0,
    WAITING_FOR_CHAT_TYPE: 1,
    WAITING_FOR_REPO_TYPE: 2,
    WAITING_FOR_SECRET_PHRASE: 3,
    WAITING_FOR_START: 4,
    WAITING_FOR_DELETING_REPO: 5
}